# Generated by Django 3.0.7 on 2020-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('email', models.CharField(max_length=150)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'store_reset_password_valification_link',
            },
        ),
        migrations.CreateModel(
            name='StoreMailVarificatioLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('email', models.CharField(max_length=150)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'store_user_mail_valification_link',
            },
        ),
    ]
