# Generated by Django 3.0.7 on 2020-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='course_categary/course.jpg', upload_to='course_categary')),
                ('language', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'course_categary',
            },
        ),
    ]
