# Generated by Django 3.0.7 on 2020-11-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=300)),
                ('language', models.CharField(max_length=30)),
                ('difficulty', models.CharField(default='Beginner', max_length=20)),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'course_categary',
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='myapp.CourseCategary')),
            ],
            options={
                'db_table': 'course_lessons',
            },
        ),
        migrations.CreateModel(
            name='UserPurchagedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'user_purchaged_course',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_link', models.CharField(max_length=150)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='myapp.CourseLesson')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
