# Generated by Django 3.0.7 on 2020-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='image',
            field=models.ImageField(default='images/course.jpg', upload_to='images'),
        ),
    ]
