# Generated by Django 3.0.7 on 2020-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200707_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategary',
            name='content',
        ),
        migrations.AddField(
            model_name='coursecategary',
            name='difficulty',
            field=models.CharField(default='', max_length=20),
        ),
    ]
