# Generated by Django 3.0.7 on 2020-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200707_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=20),
        ),
    ]
