# Generated by Django 3.0.7 on 2020-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200707_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategary',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
