# Generated by Django 3.0.7 on 2020-07-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_coursecategary_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='myapp.CourseCategary')),
            ],
            options={
                'db_table': 'course_lessons',
            },
        ),
    ]
