# Generated by Django 3.0.7 on 2020-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userpurchagedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
