# Generated by Django 3.0.7 on 2020-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200825_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategary',
            name='pub_date',
            field=models.DateTimeField(default=''),
        ),
    ]
