# Generated by Django 3.0.7 on 2020-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_coursecategary_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='pub_date',
            field=models.DateTimeField(default='2020-09-21'),
        ),
    ]
