# Generated by Django 3.0.7 on 2020-09-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200921_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='pub_date',
            field=models.DateTimeField(default='2020-09-21 12:12:12'),
        ),
    ]
