# Generated by Django 3.0.7 on 2020-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200921_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategary',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
