# Generated by Django 3.0.7 on 2020-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
