# Generated by Django 3.0.7 on 2020-07-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200709_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='created_date',
            new_name='last_login',
        ),
    ]
