# Generated by Django 3.0.7 on 2020-07-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200710_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user',
        ),
    ]
