# Generated by Django 3.0.7 on 2020-07-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200710_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mail_validate',
            field=models.IntegerField(default=0),
        ),
    ]
